#!/usr/bin/env python

Import("env")
Import("env_modules")

ecs = env_modules.Clone()

# Module source files
ecs.add_source_files(env.modules_sources, "nodes/*.cpp")
ecs.add_source_files(env.modules_sources, "storages/*.cpp")
ecs.add_source_files(env.modules_sources, "components/*.cpp")
ecs.add_source_files(env.modules_sources, "iterators/*.cpp")
ecs.add_source_files(env.modules_sources, "systems/*.cpp")
ecs.add_source_files(env.modules_sources, "resources/*.cpp")
ecs.add_source_files(env.modules_sources, "world/*.cpp")
ecs.add_source_files(env.modules_sources, "pipeline/*.cpp")
ecs.add_source_files(env.modules_sources, "*.cpp")

ecs.add_source_files(env.modules_sources, "editor_plugins/*.cpp")

