#!/usr/bin/env python

import methods_ecs

Import("env")
Import("env_modules")

ecs = env_modules.Clone()

# Module source files
ecs.add_source_files(env.modules_sources, "memory/*.cpp")
ecs.add_source_files(env.modules_sources, "components/*.cpp")
ecs.add_source_files(env.modules_sources, "iterators/*.cpp")
ecs.add_source_files(env.modules_sources, "systems/*.cpp")
ecs.add_source_files(env.modules_sources, "databags/*.cpp")
ecs.add_source_files(env.modules_sources, "world/*.cpp")
ecs.add_source_files(env.modules_sources, "pipeline/*.cpp")
ecs.add_source_files(env.modules_sources, "*.cpp")

ecs.add_source_files(env.modules_sources, "godot/components/*.cpp")
ecs.add_source_files(env.modules_sources, "godot/editor_plugins/*.cpp")
ecs.add_source_files(env.modules_sources, "godot/nodes/*.cpp")
ecs.add_source_files(env.modules_sources, "godot/databags/*.cpp")
ecs.add_source_files(env.modules_sources, "godot/systems/*.cpp")

methods_ecs.generate_dynamic_system_funcs()
methods_ecs.generate_system_exe_funcs()
methods_ecs.generate_startup_system_exe_funcs()
