#!/usr/bin/env python

Import("env")
Import("env_ecs")

env_ecs.add_source_files(env.modules_sources, "*.cpp")
env_ecs.add_source_files(env.modules_sources, "components/*.cpp")
env_ecs.add_source_files(env.modules_sources, "components/physics/*.cpp")
env_ecs.add_source_files(env.modules_sources, "editor_plugins/*.cpp")
env_ecs.add_source_files(env.modules_sources, "nodes/*.cpp")
env_ecs.add_source_files(env.modules_sources, "databags/*.cpp")
env_ecs.add_source_files(env.modules_sources, "systems/*.cpp")
