#pragma once

enum BtSpaceIndex : int {
	BT_SPACE_0 = 0,
	BT_SPACE_1 = 1,
	BT_SPACE_2 = 2,
	BT_SPACE_3 = 3,

	BT_SPACE_MAX = 4,
	BT_SPACE_NONE = BT_SPACE_MAX,
};

enum BtBodyType : int {
	BODY_TYPE_AREA = 0,
	BODY_TYPE_RIGID_BODY,
	BODY_TYPE_SOFT_BODY,
	BODY_TYPE_KINEMATIC_GHOST_BODY
};
