#!/usr/bin/env python

Import("env")
Import("env_ecs")

thirdparty_obj = []

# Add bullet header, no need to compile Bullet third party, because it's
# already done by the godot bullet module.
if env["builtin_bullet"]:
    # Build only version 2 for now (as of 2.89)
    # Sync file list with relevant upstream CMakeLists.txt for each folder.
    thirdparty_dir = "#thirdparty/bullet/"

    # Treat Bullet headers as system headers to avoid raising warnings. Not supported on MSVC.
    if not env.msvc:
        env_ecs.Append(CPPFLAGS=["-isystem", Dir(thirdparty_dir).path])
    else:
        env_ecs.Prepend(CPPPATH=[thirdparty_dir])
    if env["target"] == "debug" or env["target"] == "release_debug":
        env_ecs.Append(CPPDEFINES=["DEBUG"])

# Bullet Physics ECS
env_ecs.add_source_files(env.modules_sources, "*.cpp")
